// Copyright 2020 Cognite AS
export const SET_CDF_CLIENT = 'SET_CDF_CLIENT';

export const CLEAR_ALERTS = 'CLEAR_ALERTS';
export const SET_ALERTS = 'SET_ALERTS';

export const SET_LOADING = 'SET_LOADING';
export const SET_LOADED = 'SET_LOADED';

export const UPDATE_ASSETS = 'UPDATE_ASSETS';
export const SET_ASSETS = 'SET_ASSETS';
export const SET_ASSET = 'SET_ASSET';

export const LOGIN = 'LOGIN';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SET_LOGGED_OUT = 'SET_LOGGED_OUT';
export const SET_USER_CAPABILITIES = 'SET_USER_CAPABILITIES';
export const SET_USER_INFO = 'SET_USER_INFO';
export const LOGOUT = 'LOGOUT';

export const START_UPDATE_EVENT_INFO = 'START_UPDATE_EVENT_INFO';
export const STOP_UPDATE_EVENT_INFO = 'STOP_UPDATE_EVENT_INFO';
export const SET_EVENT = 'SET_EVENT';

export const START_UPDATE_TS_DPS = 'START_UPDATE_TS_DPS';
export const STOP_UPDATE_TS_DPS = 'STOP_UPDATE_TS_DPS';
export const SET_TS_DPS = 'SET_TS_DPS';

export const START_UPDATE_LATEST_DATAPOINT = 'START_UPDATE_LATEST_DATAPOINT';
export const STOP_UPDATE_LATEST_DATAPOINT = 'STOP_UPDATE_LATEST_DATAPOINT';
export const SET_LATEST_DATAPOINT = 'SET_LATEST_DATAPOINT';
export const SET_NEW_WIDGET = 'SET_NEW_WIDGET';

export const START_UPDATE_ALARMS = 'START_UPDATE_ALARMS';
export const STOP_UPDATE_ALARMS = 'STOP_UPDATE_ALARMS';
export const RESTART_UPDATE_ALARMS = 'RESTART_UPDATE_ALARMS';
export const SET_ALARMS = 'SET_ALARMS';
export const SAVE_REMOVED_ALARM = 'SAVE_REMOVED_ALARM';
export const SET_WIDGET_CONFIGS = 'SET_WIDGET_CONFIGS';
export const STOP_WIDGET_CONFIGS_SYNC = 'STOP_WIDGET_CONFIGS_SYNC';
