export const MAXROWS = 6;
export const MAXCOLS = 4;
export const DUMMY_COMP_ID = 'DUMMYCOMP';
export const MARGIN: any = [5, 5];
export const BREAKPOINTS = { lg: 1200 };
export const DEFAULT_LAYOUT_WIDTH = 1200;
export const IS_RESIZABLE = false;
export const MIN_WIDTH = 1000;
export const MIN_ROW_HEIGHT = 120;
